### ISSUE TITLE
[Escalated from Paystack Support]  Initializing transaction returns empty response in java

### ISSUE THREAD

**Issue by ibrahimlawal** [SeunAdelekan/PaystackJava#10]
@SeunAdelekan please we need your help with this Morufu's issue as reported below:

> I am using the java api wrapper library on my project which is maven web application running on glassfish 4.1. When I run this code, I am getting an empty json response.
> 
```java

Transactions transactions = new Transactions();
JSONObject jsonObject = new JSONObject(transactions.
initializeTransaction(AppConstants.getAlphaNumeric(20), "10000000",
"customer@email.com", "", AppConstants.getBaseUrl() + "paySuccess/" + appApiCode + "/" + usercode));
AppConstants.logger("Initializing transaction complete");
AppConstants.logger("response:"+jsonObject.toString());
```
> 
> out put:
```bash

Info: Initializing transaction
Info: Initializing transaction complete
Info: response{}
```
> When I check on https://dashboard.paystack.co/#/transactions , I can see that the transaction has gone through.

**Comment by SeunAdelekan** [comment]
Hi @ibrahimlawal, the following statement:
```java
JSONObject jsonObject = new JSONObject(transactions.initializeTransaction(AppConstants.getAlphaNumeric(20), "10000000",
"customer@email.com", "", AppConstants.getBaseUrl() + "paySuccess/" + appApiCode + "/" + usercode));
```

Should be written as:
```java
JSONObject jsonObject = transactions.initializeTransaction(AppConstants.getAlphaNumeric(20),  "10000000", "customer@email.com", "", AppConstants.getBaseUrl() + "paySuccess/" + appApiCode + "/" + usercode);
```
Feel free to contact me if any other issue arises!

**Comment by solokingjec** [comment]
Thankyou for the response. It worked. Can you kindly help me write a webhook in java for receiving payment success. Preferably a servlet.

**Comment by ibrahimlawal** [comment]
Thanks @SeunAdelekan . Glad this is sorted @solokingjec  👍  Thank you for choosing Paystack
